### ISSUE TITLE
Márgenes horizontales en el blog

### ISSUE THREAD

**Issue by Juanlu001** [APSL/PyConES-2019#1]
https://2019.es.pycon.org/blog/programa-de-ayuda-financiera/

![Screenshot_2019-06-19 PyConES 2019](https://user-images.githubusercontent.com/316517/59750414-14dc6200-927f-11e9-974c-5134861dddf6.jpg)

**Comment by aaloy** [comment]
maquetado

**Comment by Juanlu001** [comment]
Si hago click en el link:

![Screenshot_2019-06-22 https 2019 es pycon org](https://user-images.githubusercontent.com/316517/59961863-5c145e00-94de-11e9-930d-a64518c1717e.png)
