### ISSUE TITLE
Transferir repositorio

### ISSUE THREAD

**Issue by Juanlu001** [APSL/PyConES-2019#2]
Acabo de archivar https://github.com/python-spain/PyConES-2019_old y os he invitado a @aaloy y a @eduherraiz a https://github.com/orgs/python-spain/teams/pycones-2019/. Cuando tengáis un momento y si os parece bien, transferimos el repositorio a https://github.com/python-spain/PyConES-2019 :)

**Comment by aaloy** [comment]
parece que se transifirió (me obligó a cambiar url) pero ahora lo veo igual que antes y no está.
Ha habido algún problema? Se supone que el propietario del repositorio destino debe aprobarlo.

**Comment by Juanlu001** [comment]
Hmm por mi lado no he recibido nada

**Comment by Juanlu001** [comment]
¿A lo mejor hay que hacer un "unlink" de `PyConES-2017` primero?

**Comment by astrojuanlu** [comment]
Lo hablamos @eduherraiz y yo y convenimos usar https://github.com/python-spain/web-pycones para el resto de los tiempos e ir haciendo tags, en lugar de un repo cada año.
